#!/usr/bin/env bash

# Enable repositories with debug symbols packages (-dbgsym)
sudo apt-get install --assume-yes --no-install-recommends lsb-release ubuntu-dbgsym-keyring
echo "deb http://ddebs.ubuntu.com $(lsb_release -cs) main restricted universe multiverse
deb http://ddebs.ubuntu.com $(lsb_release -cs)-updates main restricted universe multiverse
deb http://ddebs.ubuntu.com $(lsb_release -cs)-proposed main restricted universe multiverse" | \
	sudo tee -a /etc/apt/sources.list.d/ddebs.list
sudo apt-get update

sudo apt-get install --assume-yes --no-install-recommends libssl-dev valgrind curl
